export const config = {
    AMD_FormContact: 'CONTACT_US',
    AMD_FormCareer: 'CAREER',
    AMD_FormCatalogue: 'CATALOG_QUOTE',
}

export const subjectConfig = {
    AMD_CAREER: 'SB_CAREER',
    AMD_QUOTE: 'SB_QUOTE',
    AMD_CATALOG: 'SB_CATALOG',
    AMD_HAVE_QUESTION: 'SB_HQUESTION',
    AMD_CONTACT_CATALOG: 'SB_CCATALOG'
}

export const ReferType = {
    AMDB_CAREER: 'AMDB_CAREER',
    AMDB_FEATURED_PRODUCTS: 'AMDB_FEATURED_PRODUCTS',
    AMDB_INFECTION_PREVENTION: 'AMDB_INFECTION_PREVENTION',
    AMDB_BLOGS: 'AMDB_BLOGS',
    AMDB_SOLUTIONS: 'AMDB_SOLUTIONS',
}

export const SEOTypeContentKey = {
    AMDB_INFECTION_PREVENTION: 'IPD_TYPE',
    AMDB_WHY_AMARYLLIS:'WHY_AMARYLLIS_TYPE',
    AMDB_OT_PACK:'OT_PACK_TYPE',
    AMDB_DISPOSABLE_GOWNS:'DISPOSABLE_GOWN_TYPE',
    AMDB_FEATURE_PROD_CONTENT:'FEATURE_CON_TYPE'
}